# Generated by Django 4.0.2 on 2022-02-11 11:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_user_coins"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Start answer",
                "verbose_name_plural": "Start answers",
            },
        ),
    ]
