# Generated by Django 4.0.2 on 2022-02-11 11:44
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_startanswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("sticker", "Sticker"),
                            ("voice", "Voice"),
                        ],
                        max_length=32,
                        verbose_name="Message type",
                    ),
                ),
                (
                    "is_forwarded",
                    models.BooleanField(
                        choices=[(True, "✅ Yes"), (False, "❌ No")],
                        default=False,
                        verbose_name="Is forwarded?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("message_text", models.TextField(verbose_name="Message text")),
                (
                    "content_hash",
                    models.CharField(max_length=128, verbose_name="MD5 content hash"),
                ),
                ("message_id", models.IntegerField(verbose_name="Message ID")),
                ("text_on_image", models.TextField(verbose_name="Text from image")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
