# Generated by Django 4.0.2 on 2022-02-11 11:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content_hash",
            field=models.CharField(
                max_length=128, null=True, verbose_name="MD5 content hash"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_text",
            field=models.TextField(null=True, verbose_name="Message text"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text_on_image",
            field=models.TextField(null=True, verbose_name="Text from image"),
        ),
    ]
