# Generated by Django 4.0.2 on 2022-02-11 13:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_message_content_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                    ("sticker", "Sticker"),
                    ("voice", "Voice"),
                    ("video_note", "Video note"),
                    ("animation", "GIF"),
                ],
                max_length=32,
                verbose_name="Message type",
            ),
        ),
    ]
