# Generated by Django 4.0.2 on 2022-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Not found meme answer',
                'verbose_name_plural': 'Not found meme answers',
            },
        ),
    ]
