# Generated by Django 4.0.2 on 2022-02-11 15:32

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_notfoundanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_position', models.CharField(choices=[('start', 'Предложение начинается на'), ('clean_start', 'Является первым словом в предложении'), ('end', 'Предложение заканчивается на'), ('clean_end', 'Является последним словом в предложении'), ('all', 'Полностью равно')], max_length=64, verbose_name='Word position')),
                ('trigger_word', models.TextField(verbose_name='Trigger word')),
                ('answer_text', models.TextField(verbose_name='Answer text')),
                ('is_interpolation_needed', models.BooleanField(choices=[(True, '✅ Yes'), (False, '❌ No')], default=False, verbose_name='Is interpolation needed?')),
                ('is_need_to_reply', models.BooleanField(choices=[(True, '✅ Yes'), (False, '❌ No')], default=False, verbose_name='Need to reply?')),
                ('is_need_to_send_quiet', models.BooleanField(choices=[(True, '✅ Yes'), (False, '❌ No')], default=False, verbose_name='Need to send quiet?')),
                ('is_case_sensitive', models.BooleanField(choices=[(True, '✅ Yes'), (False, '❌ No')], default=False, verbose_name='Is case sensitive')),
                ('answer_probability', models.IntegerField(validators=[bot.models.percent_probability_validator], verbose_name='Answer probability')),
            ],
            options={
                'verbose_name': 'Funny action',
                'verbose_name_plural': 'Funny actions',
            },
        ),
    ]
