# Generated by Django 4.0.2 on 2022-02-12 12:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_funnyaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnyaction",
            name="word_position",
            field=models.CharField(
                choices=[
                    ("start", "Предложение начинается на"),
                    ("clean_start", "Является первым словом в предложении"),
                    ("end", "Предложение заканчивается на"),
                    ("clean_end", "Является последним словом в предложении"),
                    ("all", "Полностью равно"),
                    ("any", "В любом месте"),
                ],
                max_length=64,
                verbose_name="Word position",
            ),
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(null=True, verbose_name="Amount")),
                (
                    "is_funny",
                    models.BooleanField(
                        choices=[(True, "✅ Yes"), (False, "❌ No")],
                        null=True,
                        verbose_name="Is funny?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "bet_target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_bet_user",
                        to="bot.user",
                        verbose_name="Bet target user",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.message",
                        verbose_name="Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.user",
                        verbose_name="Bet author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bet",
                "verbose_name_plural": "Bets",
            },
        ),
    ]
