# Generated by Django 4.0.2 on 2022-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_funnyaction_word_position_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(choices=[(True, '✅ Yes'), (False, '❌ No')], default=False, verbose_name='Is user deleted?'),
        ),
    ]
