# Generated by Django 4.0.2 on 2022-02-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_bet_bet_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bot_message_id',
            field=models.IntegerField(null=True, verbose_name='Bot message ID'),
        ),
    ]
