# Generated by Django 4.0.2 on 2022-02-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_bet_bet_target_user_alter_bet_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_bet_user', to='bot.user', verbose_name='Bet target user'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Bet author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='User'),
        ),
    ]
