# Generated by Django 4.0.2 on 2022-02-16 07:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0015_anekdot"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="declined_at",
            field=models.DateTimeField(null=True, verbose_name="Declined at"),
        ),
        migrations.AddField(
            model_name="bet",
            name="is_declined",
            field=models.BooleanField(
                choices=[(True, "✅ Yes"), (False, "❌ No")],
                default=False,
                verbose_name="Is declined?",
            ),
        ),
    ]
