# Generated by Django 4.0.2 on 2022-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_message_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnyaction',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('sticker', 'Sticker'), ('document', 'Document'), ('voice', 'Voice'), ('animation', 'GIF'), ('video_note', 'Video note')], default='text', max_length=32, verbose_name='Answer type'),
        ),
        migrations.AddField(
            model_name='funnyaction',
            name='file_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='File ID'),
        ),
    ]
