# Generated by Django 4.0.2 on 2022-02-23 12:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0018_funnyaction_answer_type_funnyaction_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funnyaction",
            name="answer_text",
            field=models.TextField(blank=True, null=True, verbose_name="Answer text"),
        ),
    ]
