# Generated by Django 4.0.2 on 2022-03-18 18:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0020_donate"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recognition_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Recognition type"
            ),
        ),
    ]
