# Generated by Django 4.0.2 on 2022-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_message_recognition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemotivatorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80, verbose_name='Demotivator text')),
            ],
            options={
                'verbose_name': 'Demotivator text',
                'verbose_name_plural': 'Demotivator texts',
            },
        ),
    ]
