# Generated by Django 4.0.2 on 2022-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_searchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='json_body',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON Body'),
        ),
    ]
