# Generated by Django 4.0.2 on 2022-05-26 08:06
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0025_message_json_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("h", "Helicopter")],
                default="h",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="bet_target_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="target_bet_user",
                to="bot.user",
                verbose_name="Bet target user",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.message",
                verbose_name="Message",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.user",
                verbose_name="Bet author",
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.user",
                verbose_name="From user",
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="to_user",
                to="bot.user",
                verbose_name="To user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="searchrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bot.user",
                verbose_name="User",
            ),
        ),
    ]
