# Generated by Django 4.0.2 on 2022-05-30 11:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0026_user_sex_alter_bet_bet_target_user_alter_bet_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="text_from_audio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Text from audio"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[
                    ("m", "Male"),
                    ("f", "Female"),
                    ("h", "Helicopter"),
                    ("y", "Yes"),
                ],
                default="h",
                max_length=1,
                verbose_name="Sex",
            ),
        ),
    ]
