# Generated by Django 4.0.2 on 2022-06-18 15:34
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0028_alter_bet_bet_target_user_alter_bet_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultBetAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(verbose_name="Amount"), size=5
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.user",
                        unique=True,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default bet amount",
                "verbose_name_plural": "Default bet amounts",
            },
        ),
    ]
