# Generated by Django 4.0.2 on 2022-06-18 15:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0030_alter_defaultbetamount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultbetamount",
            name="amount",
            field=models.CharField(max_length=128, verbose_name="Amount"),
        ),
    ]
