# Generated by Django 4.0.2 on 2022-06-18 17:02
import django.db.models.deletion
from django.db import migrations
from django.db import models

import bot.models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0032_alter_defaultbetamount_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultDonateAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        max_length=128,
                        validators=[bot.models.default_amount_validator],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default donate amount",
                "verbose_name_plural": "Default donate amounts",
            },
        ),
    ]
