# Generated by Django 4.0.2 on 2022-06-21 19:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0037_alter_user_permanent_nickname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="permanent_nickname",
        ),
    ]
