# Generated by Django 4.0.2 on 2022-03-18 16:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("google_vision", "0004_alter_request_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32, verbose_name="Type")),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, unique=True, verbose_name="Is main?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recognition type",
                "verbose_name_plural": "Recognition types",
            },
        ),
    ]
