# Generated by Django 4.0.2 on 2022-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_vision', '0005_recognitiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitiontype',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main?'),
        ),
    ]
